site_name: Gufo ACME
site_description: Gufo ACME Documentation
site_author: Gufo Labs
site_url: "https://docs.gufolabs.com/gufo_acme"
copyright: "&copy; 2023, Gufo Labs"
site_dir: dist/docs/
repo_url: https://github.com/gufolabs/gufo_acme/
repo_name: gufolabs/gufo_acme
nav:
  - Home: index.md
  - Installation: installation.md
  - Examples:
      - Overview: examples/index.md
      - Getting Private Key: examples/get_private_key.md
      - Generating Certificate Signing Request: examples/get_csr.md
      - Register ACME Account: examples/acme_register.md
      - Signing Certificate: examples/acme_sign.md
  - Reference: reference/
  - Developers' Guide:
      - Developer's Environment: environment.md
      - Building and Testing: testing.md
      - Common Tasks: devcommon.md
      - Code Quality: codequality.md
      - Code Base: codebase.md
      - Contributing Guide: CONTRIBUTING.md
      - Code of Conduct: CODE_OF_CONDUCT.md
      - Supported Standards: standards.md
  - FAQ: faq.md
  - Changelog: CHANGELOG.md
  - License: LICENSE.md
  # Users
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      primary: deep purple
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  features:
    - content.action.edit
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
watch:
  - docs/
  - src/gufo/
  - examples/
plugins:
  - search
  - gen-files:
      scripts:
        - docs/gen_doc_stubs.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_source: false
            show_submodules: false
markdown_extensions:
  - toc:
      permalink: True
  - admonition
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: True
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
extra:
  analytics:
    provider: google
    property: G-GW3X378HNJ
